### ISSUE TITLE
[Bug]: Go to component invalid path on windows

### ISSUE THREAD

**Issue by khalidkmas** [porifa/extension-laravel-intelephense#22]
### Bug description

On Windows, it goes to an invalid path for go to component.

Check the screenshot
![image](https://user-images.githubusercontent.com/43668507/209125068-4cd5b646-9fd4-43e8-a82a-e07fe705df14.png)

### Plugin version

1.20.1

### Operating system

Windows

### Steps to reproduce

On windows, the go-to component shows an incorrect path.
Hover over a component and you'll see the error

**Comment by AamirSohailKmAs** [comment]
Fixed in [**v1.20.2**](https://marketplace.visualstudio.com/items/Porifa.laravel-intelephense/changelog)
